import Header from "./components/header";
import HeaderInfo from "./components/headerInfo";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <HeaderInfo />
      <Header />
       <div className="pt-[3.5rem]">
          <main>
            {children}
          </main>
        </div>
        <Footer />
        {/* GHL Chat Widget */}
        <script
          src="https://beta.leadconnectorhq.com/loader.js"
          data-resources-url="https://beta.leadconnectorhq.com/chat-widget/loader.js"
          data-widget-id="68e26f349662389a78d0f3f5"
        ></script>
      </body>
    </html>
  );
}
